name: Test Prologue

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        nim-version:
          - stable
          - devel
        exclude:
          - os: macos-latest
            nim-version: devel
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v2
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-${{ matrix.nim-version}}

    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v2
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ matrix.nim-version}}-${{ hashFiles('prologue_examples.nimble') }}
        restore-keys: |
          ${{ runner.os }}-nimble-${{ matrix.nim-version}}-

    - name: Setup nim
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: ${{ matrix.nim-version }}

    - name: Install Packages
      run: nimble install -y

    - name: Install extension
      run: logue extension all

    - name: Test
      run: nimble texamples
